package com.test.Web.controllers;

import com.test.Web.models.User;
import com.test.Web.repos.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Controller
public class GreetingController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;


    @GetMapping("/")
    public String greeting(Model model) {

        return "greeting";
    }

    @GetMapping("/main")
    public String main(Model model) {
        Iterable<User> user = userRepository.findAll();
        model.addAttribute("user", user);
        return "main";
    }

    @PostMapping("/main")
    public String userAdd(@RequestParam String name,
                          @RequestParam String email, Model model) {

        User users = new User(name, email);
        userRepository.save(users);

        Iterable<User> user = userRepository.findAll();
        model.addAttribute("user", user);

        return "main";
    }

    @PostMapping("filter")
    public  String filter(@RequestParam String name, Model model) {

        Iterable<User> byName;
        if (name.length() > 0 ) {
            byName = userRepository.findByName(name);
        } else {
            byName = userRepository.findAll();
        }

        model.addAttribute("byName", byName);

        return "main";
    }
}
