package com.test.Web.controllers;

import com.test.Web.models.Message;
import com.test.Web.models.User;
import com.test.Web.repos.MessageRepository;
import com.test.Web.repos.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
public class GreetingController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    //private UserRepository userRepository;
    private MessageRepository messageRepository;


    @GetMapping("/")
    public String greeting(Model model) {

        return "greeting";
    }

    @GetMapping("/main")
    public String main(Model model) {
        Iterable<Message> messages = messageRepository.findAll();
        model.addAttribute("messages", messages);
        return "main";
    }

    @PostMapping("/main")
    public String messageAdd(
            @AuthenticationPrincipal User user,
            @RequestParam String tag,
            @RequestParam String text, Model model) {

        Message message = new Message(tag, text, user);
        messageRepository.save(message);

        Iterable<Message> messages = messageRepository.findAll();
        model.addAttribute("messages", messages);

        return "main";
    }

    @PostMapping("filter")
    public  String filter(@RequestParam String tag, Model model) {

        Iterable<Message> byTag;
        if (tag.length() > 0 ) {
            byTag = messageRepository.findByTag(tag);
        } else {
            byTag = messageRepository.findAll();
        }

        model.addAttribute("byTag", byTag);

        return "main";
    }
}
